### PR TITLE
styling for shoppingcart

### PR DESCRIPTION
**Pull request by eXtgmA**

### CODE REVIEW

**Comment by eXtgmA** [comment]
# PHPSTAN Result
```::error file=src/views/checkout.view.php,line=67,col=0::Argument of an invalid type mixed supplied for foreach, only iterables are supported.
::error file=src/views/checkout.view.php,line=67,col=0::Cannot access offset options on mixed.
::error file=src/views/checkout.view.php,line=69,col=0::Parameter #1 (mixed) of echo cannot be converted to string.
::error file=src/views/checkout.view.php,line=70,col=0::Parameter #1 (mixed) of echo cannot be converted to string.
::error file=src/views/checkout.view.php,line=86,col=0::Cannot access offset price on mixed.
::error file=src/views/checkout.view.php,line=86,col=0::Parameter #1 (mixed) of echo cannot be converted to string.
 ------ -------------------------------------------------------------- 
  Line   src/views/checkout.view.php                                   
 ------ -------------------------------------------------------------- 
  67     Argument of an invalid type mixed supplied for foreach, only  
         iterables are supported.                                      
  67     Cannot access offset options on mixed.                      
  69     Parameter #1 (mixed) of echo cannot be converted to string.   
  70     Parameter #1 (mixed) of echo cannot be converted to string.   
  86     Cannot access offset price on mixed.                        
  86     Parameter #1 (mixed) of echo cannot be converted to string.   
 ------ -------------------------------------------------------------- 


 [ERROR] Found 6 errors                                                         
```

**Comment by eXtgmA** [comment]
# PHPSTAN Result
```::error file=src/views/checkout.view.php,line=67,col=0::Argument of an invalid type mixed supplied for foreach, only iterables are supported.
::error file=src/views/checkout.view.php,line=67,col=0::Cannot access offset options on mixed.
::error file=src/views/checkout.view.php,line=69,col=0::Parameter #1 (mixed) of echo cannot be converted to string.
::error file=src/views/checkout.view.php,line=70,col=0::Parameter #1 (mixed) of echo cannot be converted to string.
::error file=src/views/checkout.view.php,line=86,col=0::Cannot access offset price on mixed.
::error file=src/views/checkout.view.php,line=86,col=0::Parameter #1 (mixed) of echo cannot be converted to string.
 ------ -------------------------------------------------------------- 
  Line   src/views/checkout.view.php                                   
 ------ -------------------------------------------------------------- 
  67     Argument of an invalid type mixed supplied for foreach, only  
         iterables are supported.                                      
  67     Cannot access offset options on mixed.                      
  69     Parameter #1 (mixed) of echo cannot be converted to string.   
  70     Parameter #1 (mixed) of echo cannot be converted to string.   
  86     Cannot access offset price on mixed.                        
  86     Parameter #1 (mixed) of echo cannot be converted to string.   
 ------ -------------------------------------------------------------- 


 [ERROR] Found 6 errors                                                         
```

**Comment by eXtgmA** [comment]
also added styling for checkout page

**Review by BBuermann-IT — APPROVED** [review]
Sieht gut aus

**Pull request merged**
