### PR TITLE
design and logic update

### PR DESCRIPTION
**Pull request by BBuermann-IT**

### CODE REVIEW

**Comment by eXtgmA** [comment]
# PHPSTAN Result
```::error file=src/controller/BookingController.php,line=125,col=0::Call to an undefined method src\controller\BookingController::store().
::error file=src/controller/OfferController.php,line=80,col=0::Method src\controller\OfferController::postDelete() has no return type specified.
::error file=src/controller/OfferController.php,line=80,col=0::Method src\controller\OfferController::postDelete() has parameter $houseId with no type specified.
::error file=src/controller/OptionController.php,line=76,col=0::Method src\controller\OptionController::postDelete() has no return type specified.
::error file=src/controller/OptionController.php,line=76,col=0::Method src\controller\OptionController::postDelete() has parameter $optionId with no type specified.
::error file=src/helper/DatabaseTrait.php (in context of class src/controller/BookingController),line=132,col=0::Method src\controller\BookingController::delete() has no return type specified.
::error file=src/helper/DatabaseTrait.php (in context of class src/controller/BookingController),line=132,col=0::Method src\controller\BookingController::delete() has parameter $id with no type specified.
::error file=src/helper/DatabaseTrait.php (in context of class src/controller/BookingController),line=132,col=0::Method src\controller\BookingController::delete() has parameter $model with no type specified.
::error file=src/helper/DatabaseTrait.php (in context of class src/controller/OfferController),line=132,col=0::Method src\controller\OfferController::delete() has no return type specified.
::error file=src/helper/DatabaseTrait.php (in context of class src/controller/OfferController),line=132,col=0::Method src\controller\OfferController::delete() has parameter $id with no type specified.
::error file=src/helper/DatabaseTrait.php (in context of class src/controller/OfferController),line=132,col=0::Method src\controller\OfferController::delete() has parameter $model with no type specified.
::error file=src/helper/DatabaseTrait.php (in context of class src/controller/OptionController),line=132,col=0::Method src\controller\OptionController::delete() has no return type specified.
::error file=src/helper/DatabaseTrait.php (in context of class src/controller/OptionController),line=132,col=0::Method src\controller\OptionController::delete() has parameter $id with no type specified.
::error file=src/helper/DatabaseTrait.php (in context of class src/controller/OptionController),line=132,col=0::Method src\controller\OptionController::delete() has parameter $model with no type specified.
::error file=src/helper/DatabaseTrait.php (in context of class src/models/BaseModel),line=132,col=0::Method src\models\BaseModel::delete() has no return type specified.
::error file=src/helper/DatabaseTrait.php (in context of class src/models/BaseModel),line=132,col=0::Method src\models\BaseModel::delete() has parameter $id with no type specified.
::error file=src/helper/DatabaseTrait.php (in context of class src/models/BaseModel),line=132,col=0::Method src\models\BaseModel::delete() has parameter $model with no type specified.
::error file=src/models/Booking.php,line=46,col=0::Method src\models\Booking::getBookedAt() should return string but returns string|null.
::error file=src/models/Bookingposition.php,line=38,col=0::Method src\models\Bookingposition::getDateStart() should return string but returns string|null.
::error file=src/models/Bookingposition.php,line=51,col=0::Method src\models\Bookingposition::getPriceDetailList() should return array<string>|null but returns array<string>|int|null.
::error file=src/models/Bookingposition.php,line=57,col=0::Method src\models\Bookingposition::setPriceDetailList() has parameter $priceDetailList with no type specified.
::error file=src/models/Option.php,line=19,col=0::Property src\models\Option::$rules type has no value type specified in iterable type array.
::error file=src/views/OptionCreate.view.php,line=14,col=0::Variable $message might not be defined.
::error file=src/views/cart.view.php,line=31,col=0::Parameter #1 (array<string>|null) of echo cannot be converted to string.
::error file=src/views/checkout.view.php,line=12,col=0::Variable $message might not be defined.
::error file=src/views/checkout.view.php,line=30,col=0::Parameter #1 (array<string>|null) of echo cannot be converted to string.
::error file=src/views/optionShowall.view.php,line=30,col=0::Variable $param might not be defined.
 ------ -------------------------------------------- 
  Line   src/controller/BookingController.php        
 ------ -------------------------------------------- 
  125    Call to an undefined method                 
         src\controller\BookingController::store().  
 ------ -------------------------------------------- 

 ------ ------------------------------------------------------------------- 
  Line   src/controller/OfferController.php                                 
 ------ ------------------------------------------------------------------- 
  80     Method src\controller\OfferController::postDelete() has no return  
         type specified.                                                    
  80     Method src\controller\OfferController::postDelete() has parameter  
         $houseId with no type specified.                                   
 ------ ------------------------------------------------------------------- 

 ------ -------------------------------------------------------------------- 
  Line   src/controller/OptionController.php                                 
 ------ -------------------------------------------------------------------- 
  76     Method src\controller\OptionController::postDelete() has no return  
         type specified.                                                     
  76     Method src\controller\OptionController::postDelete() has parameter  
         $optionId with no type specified.                                   
 ------ -------------------------------------------------------------------- 

 ------ ---------------------------------------------------------------------- 
  Line   src/helper/DatabaseTrait.php (in context of class                     
         src\controller\BookingController)                                     
 ------ ---------------------------------------------------------------------- 
  132    Method src\controller\BookingController::delete() has no return type  
         specified.                                                            
  132    Method src\controller\BookingController::delete() has parameter $id   
         with no type specified.                                               
  132    Method src\controller\BookingController::delete() has parameter       
         $model with no type specified.                                        
 ------ ---------------------------------------------------------------------- 

 ------ ---------------------------------------------------------------------- 
  Line   src/helper/DatabaseTrait.php (in context of class                     
         src\controller\OfferController)                                       
 ------ ---------------------------------------------------------------------- 
  132    Method src\controller\OfferController::delete() has no return type    
         specified.                                                            
  132    Method src\controller\OfferController::delete() has parameter $id     
         with no type specified.                                               
  132    Method src\controller\OfferController::delete() has parameter $model  
         with no type specified.                                               
 ------ ---------------------------------------------------------------------- 

 ------ ----------------------------------------------------------------------- 
  Line   src/helper/DatabaseTrait.php (in context of class                      
         src\controller\OptionController)                                       
 ------ ----------------------------------------------------------------------- 
  132    Method src\controller\OptionController::delete() has no return type    
         specified.                                                             
  132    Method src\controller\OptionController::delete() has parameter $id     
         with no type specified.                                                
  132    Method src\controller\OptionController::delete() has parameter $model  
         with no type specified.                                                
 ------ ----------------------------------------------------------------------- 

 ------ ---------------------------------------------------------------------- 
  Line   src/helper/DatabaseTrait.php (in context of class                     
         src\models\BaseModel)                                                 
 ------ ---------------------------------------------------------------------- 
  132    Method src\models\BaseModel::delete() has no return type specified.   
  132    Method src\models\BaseModel::delete() has parameter $id with no type  
         specified.                                                            
  132    Method src\models\BaseModel::delete() has parameter $model with no    
         type specified.                                                       
 ------ ---------------------------------------------------------------------- 

 ------ ------------------------------------------------------------------- 
  Line   src/models/Booking.php                                             
 ------ ------------------------------------------------------------------- 
  46     Method src\models\Booking::getBookedAt() should return string but  
         returns string|null.                                               
 ------ ------------------------------------------------------------------- 

 ------ ----------------------------------------------------------------------- 
  Line   src/models/Bookingposition.php                                         
 ------ ----------------------------------------------------------------------- 
  38     Method src\models\Bookingposition::getDateStart() should return        
         string but returns string|null.                                        
  51     Method src\models\Bookingposition::getPriceDetailList() should return  
         array<string>|null but returns array<string>|int|null.                 
  57     Method src\models\Bookingposition::setPriceDetailList() has parameter  
         $priceDetailList with no type specified.                               
 ------ ----------------------------------------------------------------------- 

 ------ -------------------------------------------------------------------------------------- 
  Line   src/models/Option.php                                                                 
 ------ -------------------------------------------------------------------------------------- 
  19     Property src\models\Option::$rules type has no value type specified                   
         in iterable type array.                                                               
         💡 See:                                                                               
            https://phpstan.org/blog/solving-phpstan-no-value-type-specified-in-iterable-type  
 ------ -------------------------------------------------------------------------------------- 

 ------ ----------------------------------------- 
  Line   src/views/OptionCreate.view.php          
 ------ ----------------------------------------- 
  14     Variable $message might not be defined.  
 ------ ----------------------------------------- 

 ------ ------------------------------------------------------------------ 
  Line   src/views/cart.view.php                                           
 ------ ------------------------------------------------------------------ 
  31     Parameter #1 (array<string>|null) of echo cannot be converted to  
         string.                                                           
 ------ ------------------------------------------------------------------ 

 ------ ------------------------------------------------------------------ 
  Line   src/views/checkout.view.php                                       
 ------ ------------------------------------------------------------------ 
  12     Variable $message might not be defined.                           
  30     Parameter #1 (array<string>|null) of echo cannot be converted to  
         string.                                                           
 ------ ------------------------------------------------------------------ 

 ------ --------------------------------------- 
  Line   src/views/optionShowall.view.php       
 ------ --------------------------------------- 
  30     Variable $param might not be defined.  
 ------ --------------------------------------- 

 [ERROR] Found 27 errors                                                        
```

**Comment by eXtgmA** [comment]
# Autofix Result
Fix code style issues automatically
```
PHPCBF RESULT SUMMARY
----------------------------------------------------------------------
FILE                                                  FIXED  REMAINING
----------------------------------------------------------------------
...l/vacation_rental/public/scripts/option-create.js  17     0
...al/vacation_rental/src/helper/ValidationTrait.php  2      0
...ntal/vacation_rental/src/helper/DatabaseTrait.php  4      0
...tion_rental/vacation_rental/src/models/Option.php  8      0
...cation_rental/vacation_rental/src/models/User.php  17     0
...n_rental/vacation_rental/src/models/BaseModel.php  5      0
...ion_rental/vacation_rental/src/models/Booking.php  6      0
...al/vacation_rental/src/models/Bookingposition.php  4      0
...ation_rental/vacation_rental/src/models/Image.php  5      0
...ation_rental/vacation_rental/src/models/House.php  6      0
...ation_rental/src/controller/BookingController.php  1      0
...acation_rental/src/controller/LoginController.php  1      0
...tion_rental/src/controller/RegisterController.php  5      0
...cation_rental/src/controller/OptionController.php  2      0
...acation_rental/src/controller/OfferController.php  6      0
...vacation_rental/src/views/createNewOffer.view.php  3      0
...ental/vacation_rental/src/views/register.view.php  1      0
----------------------------------------------------------------------
A TOTAL OF 93 ERRORS WERE FIXED IN 17 FILES
----------------------------------------------------------------------

Time: 3.65 secs; Memory: 10MB

```

**Comment by eXtgmA** [comment]
# Autofix Result
Fix code style issues automatically
```
PHPCBF RESULT SUMMARY
----------------------------------------------------------------------
FILE                                                  FIXED  REMAINING
----------------------------------------------------------------------
...ation_rental/vacation_rental/src/models/Image.php  1      0
----------------------------------------------------------------------
A TOTAL OF 1 ERROR WERE FIXED IN 1 FILE
----------------------------------------------------------------------

Time: 1.43 secs; Memory: 10MB

```

**Comment by eXtgmA** [comment]
# Autofix Result
Fix code style issues automatically
```
PHPCBF RESULT SUMMARY
----------------------------------------------------------------------
FILE                                                  FIXED  REMAINING
----------------------------------------------------------------------
...acation_rental/src/controller/LoginController.php  3      0
----------------------------------------------------------------------
A TOTAL OF 3 ERRORS WERE FIXED IN 1 FILE
----------------------------------------------------------------------

Time: 1.46 secs; Memory: 10MB

```

**Comment by eXtgmA** [comment]
# Autofix Result
Fix code style issues automatically
```
PHPCBF RESULT SUMMARY
----------------------------------------------------------------------
FILE                                                  FIXED  REMAINING
----------------------------------------------------------------------
...acation_rental/src/controller/LoginController.php  6      0
----------------------------------------------------------------------
A TOTAL OF 6 ERRORS WERE FIXED IN 1 FILE
----------------------------------------------------------------------

Time: 1.46 secs; Memory: 10MB

```

**Review by ReneSansSerif — APPROVED** [review]
meeeeega viel CONTENT am START!
APPROVED1

**Pull request merged**
